# Generated by Django 4.2 on 2023-12-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_institute_language_person_subject_thesis_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='university',
            table='UNIVERSITY',
        ),
    ]
