# Generated by Django 4.2.8 on 2024-01-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_alter_university_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thesissubject',
            table='UNIVERSITY_THESIS',
        ),
    ]
