# Generated by Django 4.2.8 on 2024-01-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_alter_thesissubject_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInstitute',
            fields=[
                ('university_id', models.OneToOneField(db_column='UNIVERSITY_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='thesis.university')),
            ],
            options={
                'db_table': 'UNIVERSITY_THESIS',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='thesissubject',
            table='THESIS_SUBJECT',
        ),
    ]
