# Generated by Django 4.2.8 on 2024-01-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_universityinstitute_alter_thesissubject_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='universityinstitute',
            table='UNIVERSITY_INSTITUTE',
        ),
    ]
